### ISSUE TITLE
Fail to install vw on python 3.7 and macOS

### ISSUE THREAD

**Issue by AlphaOlish** [VowpalWabbit/vowpal_wabbit#1764] opened 2019-02-15 16:18 UTC
Hello!

Before I've managed to install vw on macOS 10.13.6 (Darwin 17.7.0) using following: 
$ brew install boost
$ brew install boost-python3
$ /usr/local/Cellar/python/3.6.5/bin/pip3 install vowpalwabbit

Now I haven't anymore boost-python3 for python 3.6 and python 3.6 itself. 
If I do the same steps but adapted for python 3.7: 
$ brew install boost
$ brew install boost-python3
$ /usr/local/Cellar/python/3.7.2_1/bin/pip3 install vowpalwabbit
I have an error: "File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve raise DistributionNotFound(req, requirers)".

When I go here: https://formulae.brew.sh/formula/boost-python3 looks like current boost-python is linked with python 3.7.2. 
I've tried install vw via anaconda3 following instructions but it failed: 
(vowpalwabbit) useranme$ pip3 install -e vowpal_wabbit/python:
` -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- broken
    CMake Error at /usr/local/Cellar/cmake/3.13.3/share/cmake/Modules/CMakeTestCXXCompiler.cmake:45 (message):
The C++ compiler
        "/Library/Developer/CommandLineTools/usr/bin/c++"
      is not able to compile a simple test program.
      It fails with the following output:
Run Build Command:"/usr/bin/make" "cmTC_4a126/fast"
        /Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_4a126.dir/build.make CMakeFiles/cmTC_4a126.dir/build
        Building CXX object CMakeFiles/cmTC_4a126.dir/testCXXCompiler.cxx.o
        /Library/Developer/CommandLineTools/usr/bin/c++    -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.7   -o CMakeFiles/cmTC_4a126.dir/testCXXCompiler.cxx.o -c /Users/username/vw6/vowpal_wabbit/python/build/temp.macosx-10.7-x86_64-3.6/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
        warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
        1 warning generated.
        Linking CXX executable cmTC_4a126
        /usr/local/Cellar/cmake/3.13.3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4a126.dir/link.txt --verbose=1
        /Library/Developer/CommandLineTools/usr/bin/c++    -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.7 -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_4a126.dir/testCXXCompiler.cxx.o  -o cmTC_4a126
        clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
        ld: library not found for -lstdc++
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        make[1]: *** [cmTC_4a126] Error 1
        make: *** [cmTC_4a126/fast] Error 2`

Also I've tried following: 
$ brew install pyenv
$ vi ~/.bash_profile
-- set to ~/.bash_profile following: eval "$(pyenv init -)"
$ pyenv install 3.6.5
$ /.pyenv/versions/3.6.5/bin/pip3 install vowpalwabbit
And I have a usual python-boost error: 
`File "/private/var/folders/gw/ym1l4jg90zz9fyrbfb4pmqym0000gn/T/pip-build-m5o8r7cy/vowpalwabbit/setup.py", line 119, in build_extension
        env['PYTHON_LIBS'] = '-l {}'.format(find_boost())
      File "/private/var/folders/gw/ym1l4jg90zz9fyrbfb4pmqym0000gn/T/pip-build-m5o8r7cy/vowpalwabbit/setup.py", line 44, in find_boost
        raise Exception('Could not find boost python library')
    Exception: Could not find boost python library`

Could you tell me please, will vw be available via pip3.7 installation? Or what else can I try to install vw? 

Best regards, Olga.

**Comment by JohnLangford** [comment] 2019-02-21 15:42
@Scott-Graham-Bose Do you have ideas?

**Comment by AlphaOlish** [comment] 2019-02-21 15:46
I am trying now to downgrade boost, python and boost-python3: 
$ brew install boost@1.59
// install python 3.6
$ brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb
// install boost-python3 for python 3.6
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/6a77cdaac520f5d2f0a38f30606e91b7023ee5f0/Formula/boost-python3.rb

But got an error: "boost-python3: "cxx11" is not a recognized standard"

**Comment by mina1987** [comment] 2019-03-22 22:01
I have the same issue trying to install VW and libboost version  is 3.7. Any solutions?

**Comment by choltz95** [comment] 2019-04-15 15:47
Same issue. "Could not find boost python library".

**Comment by kumpera** [comment] 2019-04-15 15:57
This sounds really bad, I'll take a look at this ASAP.

**Comment by choltz95** [comment] 2019-04-15 16:03
Let me know if I can provide any info. Installation also fails for me Python2.7. I've tried the steps detailed here: https://github.com/VowpalWabbit/vowpal_wabbit/issues/1021#issuecomment-229739016 and downgrading boost. I'm on osx 10.14.4. Command line version works fine.

**Comment by robinsonkwame** [comment] 2019-05-12 21:51
Another data point here, with
```
bash-3.2$ python
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
I get a similar error:
```
 pip install vowpalwabbit
Collecting vowpalwabbit
  Using cached https://files.pythonhosted.org/packages/56/45/278a8427aa859888b3fb3e3debeea086557df8def22a23561bfe45e1fb03/vowpalwabbit-8.5.0.tar.gz
Building wheels for collected packages: vowpalwabbit
  Building wheel for vowpalwabbit (setup.py) ... error
  ERROR: Complete output from command /Users/home/.local/share/virtualenvs/jdx-reference-backend-application-TpRRN6uK/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/5q/qbskry9x44g309mf2d47j_p40000gn/T/pip-install-hchlxs07/vowpalwabbit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/5q/qbskry9x44g309mf2d47j_p40000gn/T/pip-wheel-uepz03x_ --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.6
  creating build/lib.macosx-10.9-x86_64-3.6/vowpalwabbit
  copying vowpalwabbit/pyvw.py -> build/lib.macosx-10.9-x86_64-3.6/vowpalwabbit
  copying vowpalwabbit/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/vowpalwabbit
  copying vowpalwabbit/sklearn_vw.py -> build/lib.macosx-10.9-x86_64-3.6/vowpalwabbit
  running egg_info
  writing vowpalwabbit.egg-info/PKG-INFO
  writing dependency_links to vowpalwabbit.egg-info/dependency_links.txt
  writing top-level names to vowpalwabbit.egg-info/top_level.txt
  reading manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.dll' under directory 'bin'
  warning: no previously-included files matching '*.o' found anywhere in distribution
  warning: no previously-included files matching '*.exe' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/5q/qbskry9x44g309mf2d47j_p40000gn/T/pip-install-hchlxs07/vowpalwabbit/setup.py", line 209, in <module>
      tests_require=['tox']
    File "/Users/home/.local/share/virtualenvs/jdx-reference-backend-application-TpRRN6uK/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/home/.local/share/virtualenvs/jdx-reference-backend-application-TpRRN6uK/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/home/.local/share/virtualenvs/jdx-reference-backend-application-TpRRN6uK/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/var/folders/5q/qbskry9x44g309mf2d47j_p40000gn/T/pip-install-hchlxs07/vowpalwabbit/setup.py", line 119, in build_extension
      env['PYTHON_LIBS'] = '-l {}'.format(find_boost())
    File "/private/var/folders/5q/qbskry9x44g309mf2d47j_p40000gn/T/pip-install-hchlxs07/vowpalwabbit/setup.py", line 44, in find_boost
      raise Exception('Could not find boost python library')
  Exception: Could not find boost python library
  ----------------------------------------
  ERROR: Failed building wheel for vowpalwabbit
  Running setup.py clean for vowpalwabbit
Failed to build vowpalwabbit
```

**Comment by eamag** [comment] 2019-08-15 12:54
I have this error
https://pastebin.com/TJfaqzwa
It looks like it's different from others but matches the title. I did the same steps as above

**Comment by jackgerrits** [comment] 2019-08-15 13:02
What version of MacOS are you running.

**Comment by eamag** [comment] 2019-08-15 13:23
osX 10.14.6, python 3.7, conda 4.7.10, Homebrew 2.1.10

**Comment by peterychang** [comment] 2019-08-15 15:18
It looks like this issue is caused by a change in the OSX build system in 10.9. libstdc++ was removed in favor of libc++. While we work on a fix for the problem, there appear to be two possible workarounds for this issue;
the first
https://docs.brew.sh/C++-Standard-Libraries
involves getting the missing dependency through an old version of gcc

The second
https://gitlab.kitware.com/cmake/cmake/issues/18396
involves passing compiler flags to use the correct libraries (this would require modifications to the setup.py file)

Note this workaround covers the original issue by @AlphaOlish  and the last issue by @eamag 
The second issue involving boost-python is unrelated.

**Comment by peterychang** [comment] 2019-08-22 21:40
@eamag do you by chance have the following environment variable set?
MACOSX_DEPLOYMENT_TARGET

I see your build is passing the parameter -mmacosx-version-min=10.7, but you're using the toolchain from 10.14; I believe that parameter will appear only if either your deployment target environment variable is set or if the cmake flag CMAKE_OSX_DEPLOYMENT_TARGET is passed in. The VW build scripts do not set either.

If your MACOSX_DEPLOYMENT_TARGET is set, can you try unsetting it and running the install again?

**Comment by peterychang** [comment] 2019-09-30 14:00
There are 2 separate issues here. One has been fixed as of the latest master, and the other is a problem that can't be fixed on our end, I'll outline both below.

1. For the following error
```warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9```
This is an incompatibility between your currently installed version of python and clang compiler. The version of python you are running was built with an older compiler and linked against libstdc++, which Apple has deprecated and removed from their clang releases. Attempting to link vowpalwabbit against libc++ will cause crashes.
The version of python available on Anaconda is affected by this issue. If possible please use Homebrew instead.

2. Unable to find pylibvw.so and boost-cmake errors have been resolved as of https://github.com/VowpalWabbit/vowpal_wabbit/pull/2097. These fixes will be available via pip from our next release.
For anybody unable to wait for the next release, please install the package from source.

**Closed by peterychang** 2019-09-30 14:00 UTC
Labels: Distribution Issue, Lang: Python, Platform: MacOS

**Comment by kevinkurek** [comment] 2020-09-30 00:42
I know it's not a pip solution, but for others this solved it for me on MacOSX + Python 3.7.6.
`conda install -c conda-forge vowpalwabbit `

**Comment by jackgerrits** [comment] 2020-09-30 13:08
Additionally, we have wheels produced for each commit now. Once we release 8.9 they will make it to pip so you can simply `pip install vowpalwabbit`. In the meantime check the wiki for a link to the wheel artifacts: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Python#bleeding-edge-latest-commit-on-master

**Comment by ihoment-lys** [comment] 2021-04-21 07:33
brew install boost-python3
