### ISSUE TITLE
FileNotFound Error in Uncertainty_Scores_and_Prediction_Errors

### ISSUE THREAD

**Issue by Smit-create** [VowpalWabbit/vowpal_wabbit#2309] opened 2020-03-02 10:50 UTC
While running the `vowpalwabbit/python/examples/Uncertainty_Scores_and_Prediction_Errors.ipynb`. I get the following error:
```
In[1] : os.chdir('/mnt/ryan/confidence_estimate_experiment')
Out[1]:
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-e632e0cd733b> in <module>
----> 1 os.chdir('/mnt/ryan/confidence_estimate_experiment')

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/ryan/confidence_estimate_experiment'
```

#### Environment
What version of VW did you use?
What OS or language did you use?
Ubuntu 18.04 LTS

 `VW 8.8.0 on ubuntu 18.04 LTS with the Python bindings`

.

**Comment by RituRajSingh878** [comment] 2020-03-02 11:29
`os.chdir `is just a command to change the directory. And that directory doesn't exist in your local.
So it is raising an error.

**Comment by Smit-create** [comment] 2020-03-02 12:43
Thanks @RituRajSingh878 for your response. I guess it is should be present with the examples provided so that the .`ipynb` files run without error. At the user-end, they should be able to understand the content of the` .ipynb` file by running them. So I think that we must make sure that the required file/directory is present along with the examples so they run smoothly.

**Comment by thealphadollar** [comment] 2020-03-02 15:32
This issue is a duplicate of the discussion we are having in #2303 where I and @jackgerrits are talking about the same problem. This issue can be safely closed :)

**Comment by jackgerrits** [comment] 2020-03-02 18:40
Closing this as this issue is present in #2303

**Closed by jackgerrits** 2020-03-02 18:40 UTC
