### ISSUE TITLE
Write Test For New SKLearn Based Classifier

### ISSUE THREAD

**Issue by thealphadollar** [VowpalWabbit/vowpal_wabbit#2333] opened 2020-03-10 16:13 UTC
@gramhagen [gave](https://github.com/VowpalWabbit/vowpal_wabbit/issues/2300#issuecomment-596636994) a set of helpful links for things to keep in mind when creating new estimators which we want to be compatible with SKLearn.

Here are the two links:
- http://danielhnyk.cz/creating-your-own-estimator-scikit-learn/
- https://ploomber.io/posts/sklearn-custom/

Going through both the links I found out about the `check_estimator` method present in SKLearn which we can use to test if the estimator implements all required methods or not.

I was wondering if we should add it to our contribution guidelines and also write a python test file that will run all the required checks on all the models we have present in the python folder. This will ensure that new developers can easily start with writing estimators following a particular strict style and also that no code changes break the compatibility of our models with SKLearn methods.

**Comment by RituRajSingh878** [comment] 2020-03-15 14:59
@thealphadollar  I am working on the implementation/integration of classifier and it will be helpful if we have such a feature and also, I can help here in the implementations of the `check_estmator`.
 During the implementation, we need to add or take care of lots of things, so I think a discussion will be helpful.

**Comment by thealphadollar** [comment] 2020-03-22 16:20
@RituRajSingh878 Thanks for the hand :) ALso, can you please elaborate what you mean by implement `check_estimator`? In my opinion, we just need to call it and write tests that call it automatically on each of the custom estimators we are writing.

**Comment by RituRajSingh878** [comment] 2020-03-22 16:40
I tried to do the same, but there are many problems with calling `checkestimator`. The problem is with the way we have implemented our wrapper. 
We can test by `checkestmator` by passing directly class or we can pass its object.

1- By Passing its object and it will show the following
```julia
In [1]: from sklearn.utils.estimator_checks import check_estimator                                                                                                                                          

In [2]: from vowpalwabbit.sklearn_vw import VW                                                                                                                                                              

In [3]: check_estimator(VW())                                                                                                                                                                               
Segmentation fault (core dumped)

```
I tried to find the reason behind this, but I am not able to find it.

2-By Passing class.
```julia
In [2]: from vowpalwabbit.sklearn_vw import VW                                                                                                                                                              

In [3]: check_estimator(VW)                                                                                                                                                                                 
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-1749e939b444> in <module>
----> 1 check_estimator(VW)

~/.local/lib/python3.6/site-packages/sklearn/utils/estimator_checks.py in check_estimator(Estimator)
    291         name = Estimator.__name__
    292         estimator = Estimator()
--> 293         check_parameters_default_constructible(name, Estimator)
    294         check_no_attributes_set_in_init(name, estimator)
    295     else:

~/.local/lib/python3.6/site-packages/sklearn/utils/estimator_checks.py in check_parameters_default_constructible(name, Estimator)
   2216                     assert param_value is init_param.default, init_param.name
   2217                 else:
-> 2218                     assert param_value == init_param.default, init_param.name
   2219 
   2220 

AssertionError: convert_to_vw
```
In this method, I tried to find the problem(by tracing it), and it is due to the reason behind our implementation of the class. This check fails because we have created a few new variables in the init method, and this check is not allowing it, and it is failing. 

So I am thinking that we can make a class in `VW` by inheriting the `check_estimator` and then can modify for our usage. But it will be a huge task.

**Comment by thealphadollar** [comment] 2020-03-23 09:09
Thanks for the insight, @RituRajSingh878 . I'll have a look into this when I'm free.

**Comment by gramhagen** [comment] 2020-03-24 02:21
I'm looking into this. I think we have to make some pretty significant changes to get in line with sklearn expectations. It might be worth doing though.

I'll add a draft pr soon and we can discuss the necessary changes. I believe the seg fault is happening during picking which isn't well supported yet.

**Comment by gramhagen** [comment] 2020-03-24 18:00
@RituRajSingh878 @thealphadollar please take a look at the draft pr.
I was able to get check_estimator working for the base VW() class. Let me know if there are concerns.

One thing is that this depends on sklearn >= 0.2, so we might need to enforce that / update the documentation somewhere.

**Comment by peterychang** [comment] 2020-03-24 18:04
> One thing is that this depends on sklearn >= 0.2, so we might need to enforce that / update the documentation somewhere.

>= 0.2 or 0.20? Currently the sklearn requirement is >= 0.17 (in the requirements.txt file)

**Comment by gramhagen** [comment] 2020-03-24 18:10
version 0.20 is when sklearn.utils starts filling up with helpful functions (check_array, check_X_y, check_estimator, etc.) which we're using in this change both in the implementation and in the tests.

anything >= 0.20 should be fine, this was released in sept. 2018, so I feel like we might as well draw a new line there for the 'modern' sklearn vw api work

**Comment by jackgerrits** [comment] 2020-06-25 13:58
@gramhagen it looks like #2368 resolved this? Are we okay to close?

**Comment by jackgerrits** [comment] 2021-04-01 22:40
Closing this as it looks like #2368 resolved this.

**Closed by jackgerrits** 2021-04-01 22:40 UTC
