### ISSUE TITLE
make vw_jni fails on macOS Monterey

### ISSUE THREAD

**Issue by kkchaitu27** [VowpalWabbit/vowpal_wabbit#3486] opened 2021-11-29 12:39 UTC
I am trying to build vw-jni jar on macOS Monterey.

I have followed the following steps:
git clone --recursive https://github.com/VowpalWabbit/vowpal_wabbit.git
cd vowpal_wabbit
mkdir build
cd build
cmake .. -DBUILD_JAVA=On
make vw_jni

I am facing the following issue:

[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ vw-jni ---
[INFO] Surefire report directory: /Users/krishna/Desktop/Work/Bid/vowpal_wabbit/java/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running vowpalWabbit.ClosingTest
Tests run: 8, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 0.124 sec <<< FAILURE! - in vowpalWabbit.ClosingTest
testCloseAsyncIsNearImmediate(vowpalWabbit.ClosingTest)  Time elapsed: 0.037 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1265)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1231)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
	at common.Native.try_load_from_jar(Native.java:26)
	at common.Native.<clinit>(Native.java:55)
	at vowpalWabbit.learner.VWLearners.<clinit>(VWLearners.java:22)
	at vowpalWabbit.ClosingTest.model(ClosingTest.java:185)
	at vowpalWabbit.ClosingTest.model(ClosingTest.java:171)
	at vowpalWabbit.ClosingTest.testCloseAsyncIsNearImmediate(ClosingTest.java:40)

multipleAsynchronousCloserCallsReturnTrueOnlyOnce(vowpalWabbit.ClosingTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class vowpalWabbit.learner.VWLearners
	at vowpalWabbit.ClosingTest.model(ClosingTest.java:185)
	at vowpalWabbit.ClosingTest.model(ClosingTest.java:171)
	at vowpalWabbit.ClosingTest.multipleAsynchronousCloserCallsReturnTrueOnlyOnce(ClosingTest.java:97)
....

Tests run: 40, Failures: 5, Errors: 34, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.374 s
[INFO] Finished at: 2021-11-29T16:51:06+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project vw-jni: There are test failures.

**Comment by kkchaitu27** [comment] 2021-11-30 04:49
Please find output for mvn verify -X below
[mvnverify.log](https://github.com/VowpalWabbit/vowpal_wabbit/files/7622977/mvnverify.log)

Output of ls java/target/bin/natives/linux_64/
libvw_jni.dylib

vw-jni jar is not available in maven repository for mac. I am able to compile java code by using maven dependency but when I run the application, it is looking at .so file in jar and complaining that is not a mach-O file eventhough I give libvw_jni.dylib in -Djava.library.path

**Comment by jackgerrits** [comment] 2021-11-30 14:54
When I run `mvn verify` without the binary existing in the directory I get the same error as the one you reported. I am using openjdk 17 installed using homebrew. I am not sure why but perhaps some issue stems from the other Java installation you are using, but I would not expect that to be the case.

Yes, the Jar in Maven only includes the native binary for Linux. There is an open issue to add other binaries too (https://github.com/VowpalWabbit/vowpal_wabbit/issues/1579). 

In the case of your issue it is trying to load the binary from the path and it is not able to load it. It then falls back to trying to load from the Jar and since you built it locally there is no Jar and so it is failing. https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/java/src/main/java/common/Native.java

**Comment by jackgerrits** [comment] 2022-01-13 20:10
I wasn't able to reproduce that bug and don't have a Monterey system to be able to see if that was in particular the issue. I'm going to go ahead and close this but please reach out if you are still facing this.

**Closed by jackgerrits** 2022-01-13 20:10 UTC
Labels: Bug
