### ISSUE TITLE
Update python bindings

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/vowpal_wabbit#1755] opened 2019-02-11 13:33 UTC
Latest released (on pypi) version is 8.5.0.
1) Can it be released on conda as well?
2) Can python release pipeline be more automated?

**Comment by jackgerrits** [comment] 2019-02-14 18:03
This is a duplicate of #1680, closing in favor of the existing issue.

**Closed by jackgerrits** 2019-02-14 18:03 UTC
Labels: Distribution Issue
