### ISSUE TITLE
Recent significant regression in vw training-time

### ISSUE THREAD

**Issue by arielf** [VowpalWabbit/vowpal_wabbit#1728] opened 2019-01-25 05:20 UTC
#### Describe the bug

Seeing a significant regression in training-times with latest `vw`.
The regression occurred somewhere in the past ~6 months.

#### To Reproduce

Build latest `vw` like this:
```
mkdir -p build
cd build
env CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Release -DSTATIC_LINK_VW=ON ..
make -j
# ignore some test related build errors, we only need vw itself
```

```
time ./build/vowpalwabbit/vw -k -c --passes 5000 --quiet --holdout_off -d  test/train-sets/0002.dat
18.84su 2.22ss 11.38s 185%
```

With older `vw` (built statically on July 8, 2018):
```
time ~/bin/vw -k -c --passes 5000 --quiet --holdout_off test/train-sets/0002.dat
4.65su 1.25ss 2.97s 198%
```

Used 5000 passes just to get a long enough running time.
(the regression also occurs is single pass; time is too short to reliably measure)
Progress output looks the same.

But new `vw` is nearly 4x slower to train.
 
#### Expected behavior

Expect `vw` to train as fast as it used to.

#### Observed Behavior

Training time for some data-sets like the example test above have become almost 4x slower.

#### Environment

Ubuntu 18.04
Build with `clang++` (when building with gcc, runtime is even slower) and statically linked.
Latest `vw` (cloned on 2019-01-24)

#### Additional context

I believe the problem is recent because I've been building `vw` and testing speed regularly.

**Comment by JohnLangford** [comment] 2019-01-25 12:41
I don't know any good reason for this.  

Can you binary search for the critical checkin?

**Comment by arielf** [comment] 2019-01-25 20:42
@JohnLangford yes, I plan to get to this.

Running `git bisect` got a bit complicated because of the switch to `cmake` in the middle of multiple other changes.

Speculation: I might be hitting a pathological L2/L3 cache miss because of creeping code size growth, or maybe one of the newer Intel CPU freq-down-scaling adjustments on the fly when the chip gets too hot.  This is running on a pretty new Intel(R) Core(TM) i7-8559U CPU with 256KiB L1 cache, 1MiB L2 cache, and 8MiB L3 cache.

At any rate, both are running on the same hardware.  I'll try to reproduce on different hardware and it would also help if someone else can reproduce using the older code.  I have old statically linked Linux binaries anyone to reproduce. at http://finance.yendor.com/ML/VW/Binaries

**Comment by JohnLangford** [comment] 2019-01-29 15:36
I'm wondering if the problem was the switch to cmake.   The wrong optimization flags could account for this.

**Comment by arielf** [comment] 2019-02-03 12:32
@JohnLangford thanks, indeed, good news.

Spent a long time bisecting the code to no avail.  It became obvious the problem is somewhere else. the slowness seemed to have become sticky in my work area and no `git checkout ... && make clean && make` could bring back the faster `vw`.

The cause was wrong build flags (forced to Debug).  I missed it because the compilation lines with the flags are no longer visible in the terminal (hidden by cmake wrapping).

Following the build instructions, by running:
```
cmake .. -DCMAKE_BUILD_TYPE=Release
```
followed by `make clean && make` does *not* change the build to `Release`.

Only after I edited `CMakeLists.txt`:
```
set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "Choose the type of build, options are: Debug, Release" FORCE)
```
and replaced `Debug` with `Release`, followed by `make clean; make`

The faster `vw` came back.
```
% time ./build/vowpalwabbit/vw -k -c --passes 5000 --quiet --holdout_off -d  test/train-sets/0002.dat
4.16su 0.76ss 2.47s 198%
```
This is even faster (by ~16%) than it used to be in mid 2018, possibly due to newer compiler/libs.
Adding `--onethread` drops training time by another ~15%.

A relief.

Request from the `cmake` experts to fix the instructions or code so the `CMAKE_BUILD_TYPE` flag can be changed more easily.

Thanks!

**Comment by jackgerrits** [comment] 2019-02-03 14:56
Thanks so much for looking into this! That’s a huge problem with the CMake
definition, what you did is correct and meant to have worked. I think
@kumpera may have fixed this already but I’ll talk to him and make sure
it’s fixed up.

**Comment by arielf** [comment] 2019-02-03 23:18
Thanks @jackgerrits !

**Comment by jackgerrits** [comment] 2019-02-04 14:38
I just confirmed that PR #1735 fixes the issue of `-DCMAKE_BUILD_TYPE=Release` not being picked up correctly.

As an aside, to see the command lines make is using when using the cmake generated files you can pass the VERBOSE flag like so when invoking:
```
make VERBOSE=1
```

**Comment by jackgerrits** [comment] 2019-02-11 21:34
Closing this as #1735 has been merged.

**Closed by jackgerrits** 2019-02-11 21:34 UTC
Labels: Bug
