### ISSUE TITLE
RuntimeError: std::exception when running Learning_to_Search.ipynb

### ISSUE THREAD

**Issue by hsm207** [VowpalWabbit/vowpal_wabbit#2144] opened 2019-11-17 02:08 UTC
#### Describe the bug
I get a `RuntimeError: std::exception` when executing the cell:

```
for i in range(10):
    sequenceLabeler.learn(my_dataset)
```

In the [Learning_to_Search](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/examples/Learning_to_Search.ipynb) notebook.

#### To Reproduce
Run all the cells in the  [Learning_to_Search](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/examples/Learning_to_Search.ipynb) notebook

#### Expected behavior
No RuntimeException

#### Observed Behavior
This stack trace:

![image](https://user-images.githubusercontent.com/2398765/69001902-d0361f00-0921-11ea-8bb5-7f9b36bb7fe8.png)

#### Environment
What version of VW did you use? 
8.7.0.post1

What OS or language did you use?
Ubuntu 18.04.3 LTS with Python 2.7.15 | packaged by conda-forge | (default, Feb 28 2019, 04:00:11) [GCC 7.3.0]

**Comment by jackgerrits** [comment] 2019-11-18 14:35
@lokitoth do you think this is a duplicate of #1861?

**Comment by lokitoth** [comment] 2019-11-18 15:38
I will take a look, and dupe it against the other. Let me take it for now.

**Comment by lokitoth** [comment] 2019-12-04 22:56
The issue here is due to changes to how example disposal works in the Python bindings. We mistakenly kept __enter__ when removing __exit__ in #1837.

PR #2176. removes the __enter__ call and updates the example scripts to properly dispose the generated examples (without `with`, as that is no longer supported.) Unfortunately, it seems that there was no good way to implement finish_example without the breaking change.

**Comment by lokitoth** [comment] 2019-12-05 14:59
The samples have been updated with the correct code to use in this case with #2176. LDF issues with Covington DEP Parser, and Word Alignment are tracked by #2175.

**Closed by lokitoth** 2019-12-05 14:59 UTC
Labels: Bug, In PR, L2S, Lang: Python
