### ISSUE TITLE
How To interpret VW model file

### ISSUE THREAD

**Issue by 0110G** [VowpalWabbit/vowpal_wabbit#4276] opened 2022-11-09 06:59 UTC
### Describe the bug

I am trying to use vowpal wabbit in cats mode and my use case involves online learning. These are the steps involvedL

1. Spawn new model using following args:
```       
 vw = vowpalwabbit.Workspace(
            "--cats "
            + str(self.action)
            + "  --bandwidth "
            + str(self.bandwidth)
            + " --min_value {} --max_value {} --json --chain_hash --coin --epsilon {}".format(self.min_val,
                                                                                              self.max_val,
                                                                                              self.epsilon))
```

2. To save the model, I use 
``` vw.save("model.vw")```

3. This saved model is used to serve predictions and then reloaded in backend with the args as:
```   vw = vowpalwabbit.Workspace("-i {} --json -q :: --quiet".format(filename)) ```
after which it is trained on latest data.

4. Go to step 2

For training each example, I use the following method to convert to cats json format as specified [here](https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/tutorials/python_cats.html)
```
def to_vw_example_json_format(context, cat_features, num_features, cats_label=None):
    example_dict = {}
    if cats_label is not None:
        bid, cost, pdf_value = cats_label
        example_dict["_label_ca"] = {
            "action": bid,
            "cost": cost,
            "pdf_value": pdf_value,
        }
    example_dict["c"] = {}
    for feature in cat_features:
        example_dict["c"]["{feature}={feature_value}".format(feature=feature, feature_value=str(context[feature]))] = 1
    for feature in num_features:
        example_dict["c"]["{feature}:{feature_value}".format(feature=feature, feature_value=float(context[feature]))] = 1
    return json.dumps(example_dict)
```
And eventually this to train:
```
 txt_ex = to_vw_example_json_format(context, self.config.cat_features, self.config.num_features, (action, cost, pdf_value))
 vw_format = vw.parse(txt_ex, vowpalwabbit.LabelType.CONTINUOUS)
 vw.learn(vw_format)
 vw.finish_example(vw_format)
```

And this to predict:
```
vw_text_example = to_vw_example_format(context)
return vw.predict(vw_text_example)
```

When I tried to save a model using 
```vw1 = vowpalwabbit.Workspace("-i model.vw --invert_hash model.human")```, 

Pasting first few  lines of model.human
```
Version 9.1.0
Id 
Min label:-1
Max label:1
bits:18
lda:0
0 ngram:
0 skip:
options: --bandwidth 0.001953125 --binary --cats 512 --cats_pdf 512 --cats_tree 512 --cb_explore_pdf --chain_hash --coin --epsilon 0.200000002980232 --get_pmf --max_value 1 --min_value 0 --pmf_to_pdf 512 --quadratic :: --sample_pdf --tree_bandwidth 1 --random_seed 16723685891146756571
Checksum: 1316569494
:1
initial_t 0
norm normalizer 1.29372e+08
t 126717
sum_loss 0
sum_loss_since_last_dump 0
dump_interval 1
min_label -1
max_label 1
weighted_labeled_examples 0
weighted_labels 0
weighted_unlabeled_examples 0
example_number 0
total_features 0
total_weight 1.29461e+07
sd::oec.weighted_labeled_examples 0
current_pass 0
l1_state 0
l2_state 1
14:0.00977461 40.954 40.954 1 2 20.477
29:-0.00902544 -44.3535 44.3535 1 2 22.1767
60:0.00896538 44.6506 44.6506 1 2 22.3253
63:0.0315597 0.090195 0.090195 1 0.00992318 1
82:0.00196092 204.145 204.145 1 2 102.073
93:0 101.693 101.693 1 0 101.693
100:-0.0129796 -30.84 30.84 1 2 15.42
119:-0.0832061 -4.81091 4.81091 1 2 2.40546
120:-0.0130022 -30.7865 30.7865 1 2 15.3932
121:-0.0183661 -91.893 91.893 1 6.71185 30.8929
124:-0.00315753 -310.143 310.143 1 7.66512 133.944
126:-0.0312913 -12.7924 12.7924 1 2 6.39622
127:0.00679762 -0.059022 2.3972 1 0.210799 1
139:-0.0329065 -0.0895731 0.0895731 1 0 1
152:-0.140299 -0.500891 0.500891 1 0.200642 1
162:-0.00195466 -204.8 204.8 1 2 102.4
164:-0.00195466 -204.8 204.8 1 2 102.4
```

I wanted to understand the following things:
1. How to interpret model.human file
2. The exact role of ```chain_hash``` arg. This is not very clear in vw documentation.
3. A brief about how given a context, and model.human file, how can I derive vw prediction.
4. With each training iteration, output distribution of a model for the same context changes (which is expected). However, after training, for different contexts, I do not see variance in model predictions. Can someone please guide why this is happening 

Thanks 

### How to reproduce

Provided in description itself.

### Version

9.1.0

### OS

Linux

### Language

Python

**Comment by 0110G** [comment] 2022-11-09 08:04
@olgavrou @jackgerrits

**Comment by olgavrou** [comment] 2022-11-09 14:49
Hi @0110G 

1. If you also provide the file to vw when you are doing `invert_hash` you will also get the names of the features and not only their hashes. What you are seeing now for each line is the feature hash followed by the feature's value in the model (model weight). Then you see information stored in the model in order to resume training
2. Chain hash: `Enable chain hash in JSON for feature name and string feature value. e.g. {'A': {'B': 'C'}} is hashed as A^B^C.` It means that the feature hash (location in the model) will be A^B^C and its update value will be set to `1`.
3. This is relatively straightforward to do if you are just doing regression and you can calculate the prediction using the model values. CATS is a reduction that has more than one layers (a binary prediction happens at each node of an internal routing tree and then a pdf is applied over the prediction result, etc) so it is not something that is straightforward to do by hand
4. Do you maybe have an input file for this problem so that we can take a closer look?

**Comment by jackgerrits** [comment] 2022-12-28 20:45
@0110G it looks like Olga has answered your questions, so I am going to go ahead and close this. For #4, please feel free to reopen this issue if you'd like to send an input file and we can look into it.

**Closed by jackgerrits** 2022-12-28 20:45 UTC
Labels: Bug
