### ISSUE TITLE
pip install vowpalwabbit does not proceed to install VW

### ISSUE THREAD

**Issue by aazim-lakhani** [VowpalWabbit/vowpal_wabbit#1633] opened 2018-10-12 13:37 UTC
Hello,
            I'm not trying to install VW in Linux VM. I have installed all the dependencies mentioned in earlier posts like the following. 

apt install libboost-program-options-dev zlib1g-dev libboost-python-dev libboost-all-dev

When I execute pip install vowpalwabbit _(For python version 2.7)_ or pip3 install vowpalwabbit _(for python version 3.5)_ for 20 - 30 minutes the screen remains as below 

![vw_pip_install_error](https://user-images.githubusercontent.com/3368696/46872072-05e80a80-cde8-11e8-9fc6-0adf530a47a7.JPG)

Eventually, i run out of patience. Press Ctrl C & see the following 

```
Running setup.py bdist_wheel for vowpalwabbit ... -^C^error
  Failed building wheel for vowpalwabbit
  Running setup.py clean for vowpalwabbit
Failed to build vowpalwabbit
Installing collected packages: vowpalwabbit
Failed to build vowpalwabbit
Installing collected packages: vowpalwabbit
  Running setup.py install for vowpalwabbit ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p8tfq292/vowpalwabbit/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2pu_xfvj-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/vowpalwabbit
    copying vowpalwabbit/sklearn_vw.py -> build/lib.linux-x86_64-3.5/vowpalwabbit
    copying vowpalwabbit/pyvw.py -> build/lib.linux-x86_64-3.5/vowpalwabbit
    copying vowpalwabbit/__init__.py -> build/lib.linux-x86_64-3.5/vowpalwabbit
    running egg_info
    creating vowpalwabbit.egg-info
    writing vowpalwabbit.egg-info/PKG-INFO
    writing dependency_links to vowpalwabbit.egg-info/dependency_links.txt
    writing top-level names to vowpalwabbit.egg-info/top_level.txt
    writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'src'
    warning: no files found matching '*.dll' under directory 'bin'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.exe' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    running build_ext
    make: *** No rule to make target 'clean'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-p8tfq292/vowpalwabbit/setup.py", line 209, in <module>
        tests_require=['tox']
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 49, in run
        _build_ext.run(self)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-build-p8tfq292/vowpalwabbit/setup.py", line 103, in build_extension
        prep()
      File "/tmp/pip-build-p8tfq292/vowpalwabbit/setup.py", line 63, in prep
        subprocess.check_call(['make', 'clean'], cwd=path.join(here, 'src', 'python'))
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'clean']' returned non-zero exit status 2

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p8tfq292/vowpalwabbit/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2pu_xfvj-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-p8tfq292/vowpalwabbit/
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```
I couldn't find a reason for it to fail. I would really appreciate if you could help me install vowpal. Thank you for making time to read. Really helpful reading posts from @arielf @gramhagen @Scott-Graham-Bose . Based on your experience, how much time does it take for pip install vowpalwabbit? 

More info: I'm not using any distribution for now. 

Aazim

**Comment by Scott-Graham-Bose** [comment] 2018-10-12 14:37
can you try cloning the repo, then going into the python directory and running
```python3 setup.py build```
it should provide a bit more detail about what is happening that is taking so long, feel free to report back with any errors that show up which you need help diagnosing

**Comment by aazim-lakhani** [comment] 2018-10-17 06:56
@Scott-Graham-Bose : Thank you. I did as you as said. Below are the observed logs. Please note, there was no failure. It just stopped making progress for around 30 odd minutes & knew something was definitely amiss, so I interupped it myself. 

Line where everything stops 

`g++ -std=c++11   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing -msse2 -mfpmath=sse  -D_FILE_OFFSET_BITS=64 -I /usr/local/include/boost -I /usr/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -I ../explore -c gd.cc -o gd.o
`
Last few lines before progress stops 

`g++ -std=c++11   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing -msse2 -mfpmath=sse  -D_FILE_OFFSET_BITS=64 -I /usr/local/include/boost -I /usr/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -I ../explore -c search_graph.cc -o search_graph.o
g++ -std=c++11   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing -msse2 -mfpmath=sse  -D_FILE_OFFSET_BITS=64 -I /usr/local/include/boost -I /usr/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -I ../explore -c parse_example.cc -o parse_example.o
g++ -std=c++11   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing -msse2 -mfpmath=sse  -D_FILE_OFFSET_BITS=64 -I /usr/local/include/boost -I /usr/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -I ../explore -c scorer.cc -o scorer.o
g++ -std=c++11   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing -msse2 -mfpmath=sse  -D_FILE_OFFSET_BITS=64 -I /usr/local/include/boost -I /usr/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -I ../explore -c network.cc -o network.o
g++ -std=c++11   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing -msse2 -mfpmath=sse  -D_FILE_OFFSET_BITS=64 -I /usr/local/include/boost -I /usr/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -I ../explore -c parse_args.cc -o parse_args.o
g++ -std=c++11   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing -msse2 -mfpmath=sse  -D_FILE_OFFSET_BITS=64 -I /usr/local/include/boost -I /usr/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -I ../explore -c accumulate.cc -o accumulate.o
g++ -std=c++11   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing -msse2 -mfpmath=sse  -D_FILE_OFFSET_BITS=64 -I /usr/local/include/boost -I /usr/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -I ../explore -c gd.cc -o gd.o
^C^CMakefile:37: recipe for target 'parse_args.o' failed
make[1]: *** [parse_args.o] Interrupt
Makefile:131: recipe for target 'vw' failed
make: *** [vw] Interrupt
interrupted`

**Comment by Scott-Graham-Bose** [comment] 2018-10-17 19:10
yes, the way the pip normally installs packages does not show lower level logs like this. Given this stops during a build step it is not likely related to python at all. You could try just running ```make``` from the main directory to see if it succeeds.

What linux distro are you using, and what version of g++ ?

**Comment by peterychang** [comment] 2019-08-07 17:54
The VW build process has changed significantly from when this issue was first opened. I've been unable to reproduce the issue, and seeing no updates since Oct 2018, I will be closing this ticket.

If the problem persists with VW 8.7 build, please re-open this issue and I'll take another look. Thanks

**Closed by peterychang** 2019-08-07 17:54 UTC
Labels: Distribution Issue, Lang: Python
