### ISSUE TITLE
"--audit" gives NA and unrecognizable symbols as output

### ISSUE THREAD

**Issue by adityauser** [VowpalWabbit/vowpal_wabbit#2338] opened 2020-03-14 22:15 UTC
#### Describe the bug
`--audit` sometimes gives **NA** and unrecognizable symbols as output. 

#### To Reproduce
1. For getting **NA**:
Run `vw -d train_adf.txt --cb_explore_adf --ring_size 10 --permutations   --audit `
Link to the [dataset](https://gist.github.com/AlexFridman/013c7bb7391c277b3c3e122f9f3ee2e4)
#### Observed Behavior
_Look at the highlighted line_
![Screenshot from 2020-03-15 02-55-08](https://user-images.githubusercontent.com/31898213/76690964-7d6c3a00-666b-11ea-8778-748dce11fae4.png)

2. For getting unrecognizable symbols:
Run `vw -d test/train-sets/ccb_test.dat --ccb_explore_adf  --audit`
I have tested this on [dataset1](https://github.com/VowpalWabbit/vowpal_wabbit/files/3713744/ccb_test.txt) and [dataset2](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/test/train-sets/ccb_test.dat)
#### Observed Behavior:
```
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = test/train-sets/ccb_test.dat
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0
	Action^d:100701:1:0@0	Constant:116060:1:0@0	User^b:71687:1:0@0	Slot^h:104617:1:0@0	�_id^index0:5987:1:0@0	Action^d*�_id^index0:207364:1:0@0	User^b*�_id^index0:50278:1:0@0
0
	Action^e:210597:1:0@0	Constant:116060:1:0@0	User^b:71687:1:0@0	Slot^h:104617:1:0@0	�_id^index0:5987:1:0@0	Action^e*�_id^index0:201436:1:0@0	User^b*�_id^index0:50278:1:0@0
0
	Action^f:209188:1:0@0	Constant:116060:1:0@0	User^b:71687:1:0@0	Slot^h:104617:1:0@0	�_id^index0:5987:1:0@0	Action^f*�_id^index0:150735:1:0@0	User^b*�_id^index0:50278:1:0@0
0
	Action^ff:126903:1:0@0	Constant:116060:1:0@0	User^b:71687:1:0@0	Slot^h:104617:1:0@0	�_id^index0:5987:1:0@0	Action^ff*�_id^index0:19062:1:0@0	User^b*�_id^index0:50278:1:0@0
...
...
```
This `�_id^index0` is unrecognizable.

I hope my issue makes sense.

Running the same command( `vw -d test/train-sets/ccb_test.dat --ccb_explore_adf  --audit`) on google colab throws an error
Trackback:
```
UnicodeDecodeError                        Traceback (most recent call last)

<ipython-input-74-c3c896b628b0> in <module>()
----> 1 get_ipython().system('vw -d ccb_test.txt --ccb_explore_adf  -c --ring_size 10 --permutations --ftrl --l2 0.04 --audit')

/usr/local/lib/python3.6/dist-packages/google/colab/_shell.py in system(self, *args, **kwargs)
     94       kwargs.update({'also_return_output': True})
     95 
---> 96     output = _system_commands._system_compat(self, *args, **kwargs)  # pylint:disable=protected-access
     97 
     98     if pip_warn:

/usr/local/lib/python3.6/dist-packages/google/colab/_system_commands.py in _system_compat(shell, cmd, also_return_output)
    436   # stack.
    437   result = _run_command(
--> 438       shell.var_expand(cmd, depth=2), clear_streamed_output=False)
    439   shell.user_ns['_exit_code'] = result.returncode
    440   if -result.returncode in _INTERRUPTED_SIGNALS:

/usr/local/lib/python3.6/dist-packages/google/colab/_system_commands.py in _run_command(cmd, clear_streamed_output)
    193       os.close(child_pty)
    194 
--> 195       return _monitor_process(parent_pty, epoll, p, cmd, update_stdin_widget)
    196   finally:
    197     epoll.close()

/usr/local/lib/python3.6/dist-packages/google/colab/_system_commands.py in _monitor_process(parent_pty, epoll, p, cmd, update_stdin_widget)
    220   while True:
    221     try:
--> 222       result = _poll_process(parent_pty, epoll, p, cmd, decoder, state)
    223       if result is not None:
    224         return result

/usr/local/lib/python3.6/dist-packages/google/colab/_system_commands.py in _poll_process(parent_pty, epoll, p, cmd, decoder, state)
    273       output_available = True
    274       raw_contents = os.read(parent_pty, _PTY_READ_MAX_BYTES_FOR_TEST)
--> 275       decoded_contents = decoder.decode(raw_contents)
    276 
    277       sys.stdout.write(decoded_contents)

/usr/lib/python3.6/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8c in position 500: invalid start byte
```
I guess we are getting this error because of the unrecognizable symbols.

#### Environment
What version of VW did you use?
What OS or language did you use?

 `VW 8.8.0 on Linux with the Python bindings`

**Comment by jackgerrits** [comment] 2020-03-16 21:57
That is actually the progressing validation output intertwined with the audit output. You'll notice that the columns line up with:
```
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
```

So what you're seeing is there there is no loss recording in this run so far. To see just the audit output I believe you can pass `--quiet`

**Comment by adityauser** [comment] 2020-03-16 22:09
Ohh! But why we are getting this symbol `�_id`?

**Comment by jackgerrits** [comment] 2020-03-16 22:19
Namespaces in vw are one byte in size. This is helpful because through the command line and input formats they can be represented by one character text. However, standard ASCII only occupies values 0-127 (I think). Reserved namespaces utilize the 128-255 space of the byte. This is in the extended ascii range and non standard, which is probably why it is failing to print. In this case it is `ccb_id_namespace` which is a value of 140, and is outside of the normal ASCII range. 

Short answer: This is a non-printable character by design.

Now, after saying all this it could be argued that audit mode ought to do a better job at providing insight into this.

**Comment by jackgerrits** [comment] 2020-03-19 14:09
Closing this as it is expected behavior.

**Closed by jackgerrits** 2020-03-19 14:09 UTC
