### ISSUE TITLE
python logs format have changed + logs incompleteness

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/vowpal_wabbit#3863] opened 2022-04-12 15:11 UTC
### Describe the bug
After 9.1.0 upgrade:
1) logs from pyvw got "\n" stripped from the end of every line
2) looks like logs can be incomplete

### How to reproduce

```
import vowpalwabbit
print(vowpalwabbit.__version__)

with vowpalwabbit.pyvw.Workspace(r'--cb_explore_adf -d test\train-sets\cb_adf_sm.data', enable_logging=True) as execution:
    logs = execution.get_log()
print(logs)
```

9.0.1 output:
```
9.0.1
['using no cache\n', 'Reading datafile = test\\train-sets\\cb_adf_sm.data\n', 'num sources = 1\n', 'Num weight bits = 18\n', 'learning rate = 0.5\n', 'initial_t = 0\n', 'power_t = 0.5\n', 'Enabled reductions: gd, scorer-identity, csoaa_ldf-rank, cb_adf, cb_explore_adf_greedy, shared_feature_merger\n', 'Input label = cb\n', 'Output pred = action_probs\n', 'average  since         example        example  current  current  current\n', 'loss     last          counter         weight    label  predict features\n', '2.000000 2.000000            1            1.0 0:1.5:0.25        0:0.333333...       12\n', '1.050000 0.100000            2            2.0 0:1.5:0.25        2:0.966667...       12\n', '0.500000 -0.050000            4            4.0 0:-2:0.5        2:0.9625...       16\n', '\n', 'finished run\n', 'number of examples = 4\n', 'weighted example sum = 4.000000\n', 'weighted label sum = 0.000000\n', 'average loss = 0.500000\n', 'total feature number = 52\n']
```

9.1.0 output (please see missing \n + missing tail lines):
```
9.1.0
['using no cache', 'Reading datafile = test\\train-sets\\cb_adf_sm.data', 'num sources = 1', 'Num weight bits = 18', 'learning rate = 0.5', 'initial_t = 0', 'power_t = 0.5', 'cb_type = mtr', 'Enabled reductions: gd, scorer-identity, csoaa_ldf-rank, cb_adf, cb_explore_adf_greedy, shared_feature_merger', 'Input label = cb', 'Output pred = action_probs', 'average  since         example        example        current        current  current', 'loss     last          counter         weight          label        predict features', '2.000000 2.000000            1            1.0     0:1.5:0.25         0:0.33       12', '1.050000 0.100000            2            2.0     0:1.5:0.25         2:0.97       12', '0.500000 -0.05000            4            4.0       0:-2:0.5         2:0.96       16', '']
```

### Version

9.1.0

### OS

windows

### Language

Python

**Comment by jackgerrits** [comment] 2022-04-12 15:41
The removal of `\n` was a bug fix. The intention of `get_logs` was to get each line of log messages but what was happening was that each item was some chunk of output, actually whenever flush was last called determined the chunk. [This PR](https://github.com/VowpalWabbit/vowpal_wabbit/pull/3746) implemented the line splitting. A side effect of this was the newlines were removed as they were redundant. 

In order to get the log output for the summary, `get_log` must be called after `Workspace.finish()`, so unfortunately using it with a `with` statement wont work. I am not actually sure how it worked in `9.0.1` because the output was still occurring in the `Workspace.finish()` which was still called on `__exit__`. Regardless, I think it is working as intended in `9.1.0` due to finish being the intended place this summary data gets produced.

**Comment by ataymano** [comment] 2022-04-12 17:00
Thank you, that makes sense.
Should we close it then?
'\n' removal have broken vw_executor - I am happy to make required changes there, but just wanted to point out that '\n' removal could be breaking pyvw clients similar to vw_executor.

**Comment by jackgerrits** [comment] 2022-06-23 18:50
Closing this as the described change represented a bug fix

**Closed by jackgerrits** 2022-06-23 18:50 UTC
Labels: Bug
