### ISSUE TITLE
Better performance with contextual bandit when learning probabilities incorrectly set to 0.5?

### ISSUE THREAD

**Issue by MelanieFreed** [VowpalWabbit/vowpal_wabbit#1687] opened 2018-12-11 15:30 UTC
I tried to run a simple experiment with VW for an epsilon greedy contextual bandit with two actions and two customer types ("one" and "two").  Customers of type "one" have a 4% CTR on action 1 and a 3% CTR on action 2.  Customers of type "two" have a 3% CTR on action 1 and a 4% CTR on action 2.

I ran an epsilon greedy contextual bandit (with epsilon=0.05) where I updated the model after each new incoming customer.  When I learn using the true action probabilities from the model, I get worse performance than when I (incorrectly) force the action probabilities to be 0.5 for learning.

Has anyone else seen this behavior?  Am I misunderstanding how VW should work?  Or am I doing something wrong in my implementation?

(I'm measuring performance as the overall CTR of the entire experiment.  I'm using python3 and am installing the python version of VW from release 8.6.1.  Please see below for the code and the output that I get when I run it.)

Thanks in advance!

### Code
```
import numpy as np
import pandas as pd
from vowpalwabbit import pyvw


def get_interaction(action, customer_type):

    if (customer_type == 'one' and action == 1) or \
        (customer_type == 'two' and action == 2):
        ctr = 0.04
    elif (customer_type == 'one' and action == 2) or \
        (customer_type == 'two' and action == 1):
        ctr = 0.03
    else:
        raise ValueError('Invalid action or customer_type')

    clicked = np.random.choice([True, False], p=[ctr, 1.0 - ctr])

    return clicked


def run_experiment(force_recorded_prob=False):

    model = pyvw.vw("--cb_explore 2 --epsilon 0.05 --quiet")
    num_customers = 100000
    customer_types = ['one', 'two']
    actions = [1, 2]

    num_clicks = 0
    for icustomer in range(num_customers):

        # Get customer
        customer_type = np.random.choice(customer_types, p=[0.5, 0.5])

        # Ask VW which action to show this customer
        probs = model.predict('| {}'.format(customer_type))
        probs = [round(prob, 3) for prob in probs] # Necessary b/c need to sum to 1 for python
        ichoice = np.random.choice(range(len(actions)), p=probs)
        action = actions[ichoice]
        prob = probs[ichoice]

        # Did the customer click?
        clicked = get_interaction(action, customer_type)

        # Learn
        if force_recorded_prob:
            prob = 0.5
        event = '{}:{}:{} | {}\n'.format(action,
                                         0.0 if clicked else 1.0,
                                         prob,
                                         customer_type)
        model.learn(event)

        # Save results
        if clicked:
            num_clicks += 1

    model.finish()

    ctr = 100.0 * float(num_clicks) / float(num_customers)

    return ctr


if __name__ == '__main__':

    num_experiments = 11

    force_types = [False, True]
    for force_type in force_types:
        txt = 'Using correct probabilities:' \
              if not force_type \
              else 'Using probabilities forced to 0.5 for learning:'
        print(txt)

        ctrs = []
        for ii in range(num_experiments):
            ctr = run_experiment(force_recorded_prob=force_type)
            ctrs.append(ctr)
            print('    {:2}/{:2}:  {:.3f}% CTR'.format(ii + 1, num_experiments, ctr))

        txt = '    CTR: {:.3f}% += {:.3f}% ({:.3f}% - {:.3f}%)'.format(\
            np.mean(ctrs), np.std(ctrs), min(ctrs), max(ctrs))
        print(txt)
```

### Output
```
$ python3 -m pip freeze | grep vow
-e git+git@github.com:MelanieFreed/vowpal_wabbit.git@277484317b8e09e5bda4cb4952ea8ad67961a80f#egg=vowpalwabbit&subdirectory=python
$ python3 vwtest.py 
Using correct probabilities:
     1/11:  3.587% CTR
     2/11:  3.637% CTR
     3/11:  3.546% CTR
     4/11:  3.653% CTR
     5/11:  3.648% CTR
     6/11:  3.584% CTR
     7/11:  3.665% CTR
     8/11:  3.549% CTR
     9/11:  3.539% CTR
    10/11:  3.597% CTR
    11/11:  3.568% CTR
    CTR: 3.598% += 0.044% (3.539% - 3.665%)
Using probabilities forced to 0.5 for learning:
     1/11:  3.843% CTR
     2/11:  3.794% CTR
     3/11:  4.014% CTR
     4/11:  3.934% CTR
     5/11:  3.798% CTR
     6/11:  3.978% CTR
     7/11:  3.882% CTR
     8/11:  3.932% CTR
     9/11:  3.879% CTR
    10/11:  3.825% CTR
    11/11:  3.962% CTR
    CTR: 3.895% += 0.071% (3.794% - 4.014%)
```

**Comment by JohnLangford** [comment] 2018-12-26 16:13
If you run for much longer do the performances stabilize at the same level?  If so, this is a rate of convergence issue.  If not, this is a representational issue.  I suspect the former which may be fixable by adjusting the learning rate or the way the reduction is used.  If you were using --cb_explore_adf I'd suggest using --cb_type mtr which we've found to be generally stable and good.

**Comment by MelanieFreed** [comment] 2019-01-02 19:18
Hi @JohnLangford  Thanks for your response!  The above output was created with 100k events, so I re-ran it with 1 Million events and also 10 Million events, but the results look largely the same (see below).  From your response above, it sounds like it must be a representational issue, but I'm not quite sure what you mean by that.  Could you elaborate a bit?

Results for 1 Million events:
```
Using correct probabilities:
     1/11:  3.602% CTR
     2/11:  3.618% CTR
     3/11:  3.580% CTR
     4/11:  3.584% CTR
     5/11:  3.587% CTR
     6/11:  3.596% CTR
     7/11:  3.637% CTR
     8/11:  3.606% CTR
     9/11:  3.592% CTR
    10/11:  3.579% CTR
    11/11:  3.604% CTR
    CTR: 3.599% += 0.017% (3.579% - 3.637%)
Using probabilities forced to 0.5 for learning:
     1/11:  3.880% CTR
     2/11:  3.979% CTR
     3/11:  3.916% CTR
     4/11:  3.920% CTR
     5/11:  3.905% CTR
     6/11:  3.934% CTR
     7/11:  3.876% CTR
     8/11:  3.875% CTR
     9/11:  3.925% CTR
    10/11:  3.922% CTR
    11/11:  3.937% CTR
    CTR: 3.915% += 0.030% (3.875% - 3.979%)
```

Results for 10 Million events:
```
Using correct probabilities:
     1/11:  3.665% CTR
     2/11:  3.678% CTR
     3/11:  3.685% CTR
     4/11:  3.690% CTR
     5/11:  3.672% CTR
     6/11:  3.699% CTR
     7/11:  3.689% CTR
     8/11:  3.680% CTR
     9/11:  3.688% CTR
    10/11:  3.690% CTR
    11/11:  3.695% CTR
    CTR: 3.685% += 0.010% (3.665% - 3.699%)
Using probabilities forced to 0.5 for learning:
     1/11:  3.942% CTR
     2/11:  3.941% CTR
     3/11:  3.951% CTR
     4/11:  3.948% CTR
     5/11:  3.936% CTR
     6/11:  3.941% CTR
     7/11:  3.946% CTR
     8/11:  3.949% CTR
     9/11:  3.947% CTR
    10/11:  3.945% CTR
    11/11:  3.942% CTR
    CTR: 3.944% += 0.004% (3.936% - 3.951%)
```

**Comment by JohnLangford** [comment] 2019-01-11 16:22
Something is definitely not right here, but I'm not sure what.  It's easier for me to address bugs (and will help isolate the issue) if this can be invoked from the commandline instead.  Note that you shouldn't need a large datafile since you can use --passes.

**Comment by marco-rossi29** [comment] 2019-01-17 17:12
Hi Melanie, I'm looking into this

**Comment by MelanieFreed** [comment] 2019-01-17 17:51
Thank you!!

**Comment by Kmeco** [comment] 2019-03-25 13:40
Hey @marco-rossi29 and @jackgerrits, any updates on this issue? We plan to use this setup in our project and would be very interested to know what probability values to use. Would you recommend using higher probability values to speed up learning, which is what Melanie's findings seem to imply?

**Comment by marco-rossi29** [comment] 2019-03-25 15:16
Hi @Kmeco and @MelanieFreed,
Sorry for taking time to respond. I've been investigating this issue extensively (I'm actually still focusing on it). The root issue is the bias/variance trade-off: when a constant probability is passed to the learner, bias is introduced but variance is smaller, so in some settings better results can be observed.

How many actions would you have in your real setup?

**Comment by Kmeco** [comment] 2019-03-25 16:37
Hey @marco-rossi29, thanks a lot for the quick response! 

Our setup will include ~20 actions and context with ~1000 features. 

What would you recommend?

**Comment by marco-rossi29** [comment] 2019-05-23 01:51
I'm closing this issue and we can take the discussion offline

**Closed by marco-rossi29** 2019-05-23 01:51 UTC
Labels: Bug, Priority: High

**Comment by ahorn** [comment] 2020-09-09 03:32
I have repeated the experiment by @MelanieFreed with version 8.8.1 of VW, and I was able to reproduce the original result:

```
Using correct probabilities:
     1/11:  3.536% CTR
     2/11:  3.562% CTR
     3/11:  3.638% CTR
     4/11:  3.586% CTR
     5/11:  3.454% CTR
     6/11:  3.628% CTR
     7/11:  3.598% CTR
     8/11:  3.568% CTR
     9/11:  3.615% CTR
    10/11:  3.601% CTR
    11/11:  3.642% CTR
    CTR: 3.584% += 0.052% (3.454% - 3.642%)
Using probabilities forced to 0.5 for learning:
     1/11:  3.851% CTR
     2/11:  3.824% CTR
     3/11:  3.892% CTR
     4/11:  3.993% CTR
     5/11:  3.867% CTR
     6/11:  3.972% CTR
     7/11:  3.763% CTR
     8/11:  3.846% CTR
     9/11:  3.881% CTR
    10/11:  3.861% CTR
    11/11:  3.949% CTR
    CTR: 3.882% += 0.064% (3.763% - 3.993%)
```

Since this experimental setup seems reasonable, and @JohnLangford marked the issue as a bug, I wanted to check on the expected behavior.

Is there anything that I, as a user of VW, can or should do to avoid similar unexpected results? For instance, should I choose the values for probabilities in a certain way?

**Comment by JohnLangford** [comment] 2020-09-09 13:24
An option was added to VW to truncate probabilities that become to small (--clip_p <x>).  The right value of <x> is dependent on the problem set, so we are still thinking about how to have an automatic solution.
