### ISSUE TITLE
TestJsonDictClass fails randomly

### ISSUE THREAD

**Issue by olgavrou** [VowpalWabbit/vowpal_wabbit#2527] opened 2020-07-23 17:34 UTC
Example of failed run [here](https://dev.azure.com/vowpalwabbit/Vowpal%20Wabbit/_build/results?buildId=11736&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997)

**Comment by jackgerrits** [comment] 2020-07-23 17:36
@lokitoth I remember you looked into this a while back. What did you discover?

**Comment by jackgerrits** [comment] 2021-04-08 20:05
Closing as duplicate of  #1978

**Closed by jackgerrits** 2021-04-08 20:05 UTC
Labels: Bug
