### ISSUE TITLE
Initial weight flag is ignored for practical purposes when using coin.

### ISSUE THREAD

**Issue by mrucker** [VowpalWabbit/vowpal_wabbit#3614] opened 2022-01-18 18:25 UTC
#### Describe the bug
When using `--coin`, VW feature weights are set to 0 after the first learn iteration regardless of the `--initial_weight` flag.

#### To Reproduce

1. Used this specific command line `vw -a -d test --initial_weight 1 --coin`
3. Used this `test` file
1 |x 0:1 |a 0:1
0 |x 0:2 |a 0:2
1 |x 0:3 |a 0:3

#### Expected behavior
We expected that setting initial_weight would alter the performance of our learner.

#### Observed Behavior
Setting initial_weight to a value other than its default value did not alter the performance of our learner. When we look at the actual weights in VW they do all appear to be 1 until learn is called for the first time. This can be seen both in the Python interface where one can control when learn is called and using the audit flag (`-a`) in the CLI. Below is a screenshot of the behavior in Python. You can see that before learn is called all feature weights have a value of 1 (our initial_weight value) after learn all feature weights are 0.

![image](https://user-images.githubusercontent.com/966578/149995185-59766364-c0ec-41bd-b158-ca86e3277a7b.png)

#### Environment
What version of VW did you use? 8.10.1
What OS or language did you use? Python and Ubuntu

#### Additional context
I'm not completely sure but I think the problem is this line [here](https://github.com/VowpalWabbit/vowpal_wabbit/blob/44a056bbdd3af13d6c0c80dae6848a8a69d98e39/vowpalwabbit/ftrl.cc#L213).

**Comment by ataymano** [comment] 2022-01-20 15:58
It actually happens because w[W_ZT] is updated after this line:
w[W_XT] = (...) * w[W_ZT]
https://github.com/VowpalWabbit/vowpal_wabbit/blob/44a056bbdd3af13d6c0c80dae6848a8a69d98e39/vowpalwabbit/ftrl.cc#L211
looking deeper.

**Comment by ataymano** [comment] 2022-01-27 15:13
Sorry for delay in response.
Update rule for weights in coin betting is not in the form of:
w_{t+1} = w_t + X
So looks like "initial weight" as concept is not applicable here.
@bremen79, can you please confirm if it is fair to say that?

**Comment by jackgerrits** [comment] 2022-01-27 19:00
Based on @ataymano's comment it seems this is expected behavior so I am going to go ahead and close this. @bremen79, please chime in if that is incorrect

**Closed by jackgerrits** 2022-01-27 19:00 UTC
Labels: Bug

**Comment by bremen79** [comment] 2022-01-27 22:48
Coin-betting is based on FTRL and in FTRL the "initial weight" has a different meaning: basically instead of optimizing F(x), we optimize F(x+x0), where x0 is the initial weight. So, it can be added but we have to store x0 somewhere and add it at every iteration. 
I implemented it like this in COCOB (https://arxiv.org/abs/1705.07795) and it is implemented in the same way in recent FTRL based optimizers (for example https://arxiv.org/pdf/2010.10502.pdf).
I guess it is up to you if you want to implement it or not.

**Comment by mrucker** [comment] 2022-02-04 15:53
That all makes sense. Thanks for taking the time to give a detailed response and suggested directions!
