### ISSUE TITLE
vw in --active mode crashes when a connection is opened on Windows

### ISSUE THREAD

**Issue by ZechyW** [VowpalWabbit/vowpal_wabbit#2405] opened 2020-04-15 08:19 UTC
#### Describe the bug
When vw has been started in --active mode on Windows, opening a connection to the daemon causes it to crash.

#### To Reproduce
1. Build VW from source on Windows 10, using Visual Studio 2017
2. Run `vw --active`
3. Connect to the daemon on the running port

#### Expected behavior
VW should enter interactive active learning mode.

#### Observed Behavior
VW crashes with the following error:
```
Debug Assertion Failed!

Program: <...>\vw.exe
File: minkernel\crts\ucrt\src\appcrt\lowio\read.cpp
Line: 380

Expression: fh >= 0 && (unsigned)fh < (unsigned)_nhandle

...
```

#### Environment
VW 8.8.1 on Windows 10 compiled with Visual Studio 2017.

#### Additional context
Any help would be appreciated!

**Comment by jackgerrits** [comment] 2020-04-15 12:17
Hi @ZechyW, are you able to provide the data file used to repro this?

**Comment by ZechyW** [comment] 2020-04-15 12:55
Hi @jackgerrits, vw crashes the moment a connection is opened, so there isn't a data file used per se -- I've tried it both with `active_interactor.py` from the repo as well as with a minimal TCP client, and in both cases it doesn't get past the connection stage.

**Comment by jackgerrits** [comment] 2020-04-15 12:57
Okay I see, what is the entire command line for both the daemon and client?

**Comment by ZechyW** [comment] 2020-04-15 13:11
For the daemon, I'm running `vw --active --port 6075`.
For the client, I've trying to open the connection directly in Python:
```python
import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect(("localhost", 6075))
```

**Comment by jackgerrits** [comment] 2020-04-15 13:12
Okay thanks, I'll take a look!

**Comment by ZechyW** [comment] 2020-04-15 13:14
Much appreciated!

**Comment by jackgerrits** [comment] 2020-04-15 13:44
The issue is that on Windows it seems that the socket detection function isn't working correctly. Specifially it seems that using `_getmaxstdio()` did not age well.

https://github.com/VowpalWabbit/vowpal_wabbit/blob/f94d8def9ed56b94d67b4985afd36a8641942fcd/vowpalwabbit/io_buf.cc#L114

This code is in need of a refactor that would resolve an issue like this but I want to try and work out a solution faster than that to get you unblocked. @ZechyW, it seems to me that this issue is not present on Linux so you could possibly run the daemon in WSL or something to get you unblocked. I'll work on a solution to get his functionality fixed on Windows in the meantime.

**Comment by ZechyW** [comment] 2020-04-16 02:05
Thanks for your help @jackgerrits, can confirm that vw in active learning mode works as expected when built and run on WSL.

**Comment by jackgerrits** [comment] 2020-04-21 20:34
@ZechyW, if you are able to would you be able to confirm if PR #2412 solves the issue?

**Comment by ZechyW** [comment] 2020-04-22 01:50
Hi @jackgerrits, yes, can confirm that the changes fix the active learning mode connection issues on Windows 10 -- Thanks for the update!

**Closed** 2020-05-15 13:24 UTC
Labels: Bug, Platform: Windows
