### ISSUE TITLE
How to use cache format of examples in daemon mode?

### ISSUE THREAD

**Issue by igor-susic** [VowpalWabbit/vowpal_wabbit#4497] opened 2023-02-14 11:13 UTC
### Description

Hi I'm hoping to get this native format clarified a bit.

In documentation for input format:
- https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/command_line_args.html#input-options

It stands that:
> Parsing raw data is slow so there are options to create or load data in VW’s native format. Files containing data in VW’s native format are called caches. The exact contents of a cache file depend on the input as well as a few options (-b, --affix, --spelling) that are passed to VW during the creation of the cache. This implies that using the cache file with different options might cause VW to rebuild the cache. The easiest way to use a cache is to always specify the -c option. This way, VW will first look for a cache file and create it if it doesn’t exist. To override the default cache file name use --cache_file followed by the file name.

When looking at the source code, function `set_daemon_reader` has option to read input in this native format:

- https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/core/src/parser.cc#L209

If I understood everything correctly I could encode my examples to this native format while sending them over `TCP` to my `vw daemon` in that case I guess pre-processing would be much faster and that would result with faster serving also instead of sending raw text as `bytes`. The problem is, that it's not really clear to me how to encode my example to this native format if I have only one example that I would want to send over network and get some predictions back. Could you shed a little light on me for this one?

I have tried googling and only stuff that I could find is to use this cache while training which is dealt automatically by `vw` when you use the right flags like `-c` when training. 

Thank you

**Comment by jackgerrits** [comment] 2023-02-14 12:05
The sender reduction communicates with a daemon mode vw using cache format, so it's a sample that can be used to understand what is going on. (https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/core/src/reductions/sender.cc)

When it comes to cache and daemon mode there are a few things to explain.

- When VW connects a socket during daemon mode it tries to determine if it is for binary or text input. The binary detection reads a single byte and checks if it is `\0`. So, if you make a socket connection from elsewhere you need to make sure you handshake with this value.
- Cache files have a header with version information which isn't required (in fact can't be sent) when sending cache examples to a daemon reader
- From C++ [`VW::parsers::cache::write_example_to_cache`](https://github.com/VowpalWabbit/vowpal_wabbit/blob/1098efd3e67d1ad913bec1712e6bc52074f884a3/vowpalwabbit/cache_parser/include/vw/cache_parser/parse_example_cache.h#L43) can be used to produce a single example's worth of cache format
- For Python, using the [new bindings](https://github.com/VowpalWabbit/py-vowpal-wabbit-next), you can peek behind the curtains and call what the bindings use to write a single example to the cache file. (https://github.com/VowpalWabbit/py-vowpal-wabbit-next/blob/e3f73bd20257cf24ed88b4104e7c148a3abd8ecd/src/vowpal_wabbit_next/cache_format.py#L117). The result of this could be sent over the socket.

Hopefully that helps! Let me know if you have further questions

**Comment by igor-susic** [comment] 2023-02-14 15:06
Thanks for the information @jackgerrits in this case I would love to use something like [`VW::parsers::cache::write_example_to_cache`](https://github.com/VowpalWabbit/vowpal_wabbit/blob/1098efd3e67d1ad913bec1712e6bc52074f884a3/vowpalwabbit/cache_parser/include/vw/cache_parser/parse_example_cache.h#L43) but from the `Go` language.

I see that there is `c_wrapper` component but it's described as old `C` API which makes me wonder is there a new `C` API? Also `cache` format is currently not exposed there. The reason why I am asking this is that in `Go` it is much easier to do `C` bindings then `C++` binding  which I would like to avoid just because I have a need to call one function.

If needed I'm available to contribute for this type of thing but before anything happens obviously I would need a bit of your guidance.

**Comment by jackgerrits** [comment] 2023-02-14 15:14
The C bindings that exist in this repo are pretty limited, and have the critical issue of lacking the ability to report errors. I created a C API for use with the Rust bindings which can report errors, although I wouldn't consider it a public API nor is it stable.  Cache is also not exposed and so would need to be added. Despite being in that repo, there isn't anything really Rust specific in the C API itself.

https://github.com/jackgerrits/vowpalwabbit-rs/blob/master/binding/include/vw_rs_bindings/bindings.hpp

**Comment by igor-susic** [comment] 2023-02-14 16:08
Well if I add the function that converts `example` to `native` format for starters (that's all I need now) it wouldn't be much of problem I guess to expose it there and the bindings for `Go` I would generate in my project just as you did for `Rust`. If there would be a request for something more serious for `Go` then it's different story but for starters this is fine if you agree. Either that or some `doc` that explains this `native` standard if someone want's to implement it but probably the first is better now not sure what do you think about it.

**Comment by jackgerrits** [comment] 2023-02-14 17:50
The problem is that the API is out in the wild and used, so we can't change the interface to return error codes. So, any thrown exception is thrown across the C boundary. It's clearly a problem and it means it isn't really a C API but actually a C++ API that looks close to a C API.

If you wish to add just the function you need, that's totally fine. No need to do something more serious for Go. We don't want to standardize the cache format. It is intentionally an unstable implementation detail.

Daemon mode also has no way of reporting errors.

**Comment by lalo** [comment] 2023-02-14 22:06
python impl: https://github.com/VowpalWabbit/py-vowpal-wabbit-next/blob/e3f73bd20257cf24ed88b4104e7c148a3abd8ecd/src/main.cpp#L395

**Comment by igor-susic** [comment] 2023-02-16 08:46
Thanks for the help, will try it out first locally and if everything works as expected will push `PR` for this addition.

**Comment by igor-susic** [comment] 2023-02-20 10:58
I have few questions @jackgerrits about this would appreciate the help.


- I want to clarify when you say handshake with `\0` you just mean first thing I write on this connection should be `\0` after TCP handshake or? I see that you set the `sin_zero` to `\0` so not sure what's up with that (source: `VW::details::open_vw_binary_socket` `9.7.0`)

- If we have examples that are from CB like the ones below and we need prediction for this:

````
['shared |User user=Anna time_of_day=morning',
 '|Action article=politics',
 '|Action article=sports',
 '|Action article=music',
 '|Action article=food',
 '|Action article=finance',
 '|Action article=health',
 '|Action article=camping']
````

After encoding each line to `cache` format is it ok to just assume that we need to concatenate all these bytes in one big array and send that to the daemon to run predictions?



- Third question relates to my local tests as at my local branch (which is cloned from `9.6.0`) I added following code
```c++

  VW_DLL_PUBLIC size_t VW_CALLING_CONV VW_WriteExampleToCache(VW_HANDLE handle, VW_EXAMPLE example, char* out) {
    auto* pointer = static_cast<VW::workspace*>(handle);
    auto* ex = static_cast<VW::example*>(example);

    VW::details::cache_temp_buffer temp_buffer;
    io_buf output;

    VW::write_example_to_cache(output, ex, pointer->example_parser->lbl_parser, pointer->parse_mask, temp_buffer);
    size_t max_size = output.unflushed_bytes_count();

    output.copy_to(out, max_size);

    return max_size;
  }
```

And I would expect this to write me the same bytes as the `CacheFormatWriter.write_example()` from `py-vowpal-wabbit-next` if we ignore the header which is I guess first 19 bytes that writes some version info etc.

The input example for `VW_WriteExampleToCache` would be result of `VW_ReadExampleA` from `C` API meanwhile the input example in `py` would be result of `TextFormatParser.parse_line()` where raw input for both examples is `shared |User user=Anna time_of_day=morning`.


Now when checking bytes written to a file and the ones I got with `VW_WriteExampleToCache` they defer like this:
```
This is result from VW_WriteExampleToCache
31000000 00000000 00000000 0000803F 00000000 00000000 00000000 30025506 00000000 000000A0 8415A0DC 46800300 00000000 000080D7 62
```

```
I guess this is the header
06000000 00000000 392E372E 30006312 000000
This is result from Py API 
31 00000000 00000001 000000FF FF7F7F60 34561500 0080BF00 00000000 00803F00 00000000 00000030 01550600 00000000 000088A1 4588D731
```


Last question is unrelated to the cache format, just wondering why daemon doesn't send `EOF` never after it returns the `pmf` values it just uses `\n\n` ?



Thank you

**Comment by igor-susic** [comment] 2023-02-21 18:53
So to connect on my previous comment, I kinda confirmed that:

-  First thing you need to write to socket is zero byte if you want input to be considered as cache format (binary)
-  After encoding each line to cache format it seems ok to concatenate all these bytes in one big array and send that to the daemon to run predictions. 


The issue comes when running my modifications locally (for C API) I actually get the return:

`0:0.142857,1:0.142857,2:0.142857,3:0.142857,4:0.142857,5:0.142857,6:0.142857` 

for my cache format data sent over the network. Obviously `vw` recognises right number of actions etc. but the issue is that the result should be:

 `1:0.828571,0:0.028571,5:0.028571,4:0.028571,3:0.028571,6:0.028571,2:0.028571` 

I'm not seeing that result I guess because of the difference in in these cache encodings which I described above either that or something else missing, but the help on this last one would mean a lot @jackgerrits if you could take a look in that `C/C++` code above am I missing something there 👁️

**Comment by igor-susic** [comment] 2023-02-22 12:10
Update on this issue, seems that all the fault for different byte conversion was when getting an example from C API. Function `VW_ReadExampleA(VW_HANDLE handle, char* line)` calls `VW::example* read_example(VW::workspace& all, const char* example_line)`  which in turn calls `setup_example(all, ret)`. The `setup_example(all, ret)` does something to the `Example` which changes stuff up. I eliminated this in my tests by implementing new function in C API to parse one example:

```c++

VW_DLL_PUBLIC VW_EXAMPLE VW_CALLING_CONV VW_ReadLine(VW_HANDLE handle, char* in) {
    auto* pointer = static_cast<VW::workspace*>(handle);
    VW::example* ex_out = &get_unused_example(pointer);

    std::string line(in);
    VW::read_line(*pointer, ex_out, line);

    return static_cast<VW_EXAMPLE>(ex_out);
  }
```

After this one everything works as expected. Now I'm not sure how to think about it as I'm not that familiar with this code base but I would like to push PR to enable having this if that's fine as we agreed.  

Sorry for wall of text before this one, now in retrospective I see it kinda served me as rubber duck 👀

**Comment by jackgerrits** [comment] 2023-02-22 14:52
There is already a function which can read an example from text format, see here: https://github.com/VowpalWabbit/vowpal_wabbit/blob/6aac4e00e32d8f04de254f17ac6719d153c93f2d/vowpalwabbit/c_wrapper/src/vwdll.cc#L150

`setup_example` does change an example, however, the cache format actually expects the content of the example prior to calling setup. (This is confirmed by noticing that `setup_example` is actually the hook to output cache files in CLI VW and it is the first thing it does in the function)

One thing you may be missing is that it looks like you're using multi-line examples. You need to send a "newline" example to signal the end of one example. This can be seen in the Python cache writer implementation (https://github.com/VowpalWabbit/py-vowpal-wabbit-next/blob/f24560d1e7d5d861f52e215200971bff2da7bead/src/vowpal_wabbit_next/cache_format.py#L120)

A newline example can be created by parsing an empty line (https://github.com/VowpalWabbit/py-vowpal-wabbit-next/blob/f24560d1e7d5d861f52e215200971bff2da7bead/src/vowpal_wabbit_next/cache_format.py#L93)

It's still not clear to me what was going wrong in your initial attempts.

**Comment by jackgerrits** [comment] 2023-02-22 15:03
One other thing, when using a `VW::io_buf`, you need to give it backing storage. An `io_buf` on it's own cannot persist, and it seems we don't check in release mode for the existence of a backing file. You can use an in memory buffer, see here:
https://github.com/VowpalWabbit/vowpal_wabbit/blob/b89b4242de64efb0df0cb6601a7126e893001f96/vowpalwabbit/core/tests/slates_parser_test.cc#L118

Then when you are done writing the cache, flush the io_buf and read the backing vector.

**Comment by igor-susic** [comment] 2023-02-22 19:19
> There is already a function which can read an example from text format, see here:
 
Well I was calling that same function and that was causing me the issue, but **_important_** thing to note is that I was **_working with code on `9.6.0` tag version._**  

As you said here:
> setup_example does change an example, however, the cache format actually expects the content of the example prior to calling setup. (This is confirmed by noticing that setup_example is actually the hook to output cache files in CLI VW and it is the first thing it does in the function)

This is true and actually the function you have referenced above
https://github.com/VowpalWabbit/vowpal_wabbit/blob/6aac4e00e32d8f04de254f17ac6719d153c93f2d/vowpalwabbit/c_wrapper/src/vwdll.cc#L150

In the version `9.6.0` calls `setup_example` here
https://github.com/VowpalWabbit/vowpal_wabbit/blob/16e9114f41343eed0a5f3f9881b171ce4ea6774a/vowpalwabbit/core/src/parser.cc#L793

Which would make my workflow go like this:

1. Initialize workspace using https://github.com/VowpalWabbit/vowpal_wabbit/blob/16e9114f41343eed0a5f3f9881b171ce4ea6774a/vowpalwabbit/c_wrapper/src/vwdll.cc#L63
2. Convert string to and `example` using https://github.com/VowpalWabbit/vowpal_wabbit/blob/16e9114f41343eed0a5f3f9881b171ce4ea6774a/vowpalwabbit/c_wrapper/src/vwdll.cc#L142
3. Now call my custom function `VW_WriteExampleToCache`

The issue was **at step `2.`** as before passing the example to cache format `**setup_example**` was called on that example.

I will try it out on `9.7.0` and `master` to see what has changed in the meantime, maybe the code doesn't run in the same way.

**Comment by jackgerrits** [comment] 2023-02-22 20:00
Ah I see what you're saying. I didn't realize that function calls `setup_example`. That is certainly the issue you were facing and `9.7.0` won't help.

That is a footgun for sure. These APIs are hard to use without knowing what's going on inside. Nice work working that one out.

This is precisely the reason why I removed the concept of "setup" from the new Python bindings I am working on as they are a confusing implementation detail.

**Comment by jackgerrits** [comment] 2023-03-21 00:07
I'm going to go ahead and close this one, please feel free to reopen or open a new issue if you have further questions

**Closed by jackgerrits** 2023-03-21 00:07 UTC
Labels: Documentation
