### ISSUE TITLE
conda_install.sh failed

### ISSUE THREAD

**Issue by liyinan1001** [VowpalWabbit/vowpal_wabbit#1792] opened 2019-03-19 00:08 UTC
OS: Ubuntu 16.04.
I successfully installed vw and happily used it. Now I want to use vw python wrapper. I tried executing vowpal_wabbit/python/vowpalwabbit/conda_install.sh https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/python/vowpalwabbit/conda_install.sh. However, the last command in the script failed:

```
Installing collected packages: vowpalwabbit
  Running setup.py develop for vowpalwabbit
    Complete output from command /home/yinan.li1/anaconda3/bin/python -c "import setuptools, tokenize;__file__='/home/yinan.li1/workspace/vowpal_wabbit/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing vowpalwabbit.egg-info/PKG-INFO
    writing dependency_links to vowpalwabbit.egg-info/dependency_links.txt
    writing top-level names to vowpalwabbit.egg-info/top_level.txt
    reading manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'src'
    warning: no files found matching '*.dll' under directory 'bin'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.exe' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    running build_ext
    cmake /home/yinan.li1/workspace/vowpal_wabbit/python/.. -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/yinan.li1/workspace/vowpal_wabbit/python -DCMAKE_BUILD_TYPE=Release -DPY_VERSION=3.6 -DBUILD_PYTHON=On -DWARNINGS=Off
    -- VowpalWabbit Version: 8.6.1
    -- Number of processors: 20
    -- Boost version: 1.58.0
    -- Found the following Boost libraries:
    --   program_options
    --   system
    --   thread
    --   unit_test_framework
    --   chrono
    --   date_time
    --   atomic
    -- help2man not found, please install it to generate manpages
    -- Python 3.6 will be used for VowpalWabbit Python bindings
    CMake Error at /home/yinan.li1/anaconda3/lib/python3.6/site-packages/cmake/data/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
      Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
      (Required is at least version "3.6")
    Call Stack (most recent call first):
      /home/yinan.li1/anaconda3/lib/python3.6/site-packages/cmake/data/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
      /home/yinan.li1/anaconda3/lib/python3.6/site-packages/cmake/data/share/cmake-3.11/Modules/FindPythonLibs.cmake:261 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      python/CMakeLists.txt:21 (find_package)


    -- Configuring incomplete, errors occurred!
    See also "/home/yinan.li1/workspace/vowpal_wabbit/python/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    See also "/home/yinan.li1/workspace/vowpal_wabbit/python/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
    error: command 'cmake' failed with exit status 1

    ----------------------------------------
Command "/home/yinan.li1/anaconda3/bin/python -c "import setuptools, tokenize;__file__='/home/yinan.li1/workspace/vowpal_wabbit/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/yinan.li1/workspace/vowpal_wabbit/python/
```

**Comment by jackgerrits** [comment] 2019-03-19 14:34
It looks like the conda path is missing the python dev libraries. Normally this is installed using `sudo apt-get install python-dev`, but when it is using the conda path then I am assuming either conda needs to be installed as a dev version or you need to install the python libs to the conda path.

**Comment by liyinan1001** [comment] 2019-03-20 21:00
> It looks like the conda path is missing the python dev libraries. Normally this is installed using `sudo apt-get install python-dev`, but when it is using the conda path then I am assuming either conda needs to be installed as a dev version or you need to install the python libs to the conda path.

I did `sudo apt-get install python-dev` and it says it's already installed. How do I install a conda dev version? And how to install the python libs to conda path?

**Comment by ataymano** [comment] 2019-03-22 18:26
Reproduced, looking.

**Comment by peterychang** [comment] 2019-04-12 20:37
Should be fixed with https://github.com/VowpalWabbit/vowpal_wabbit/pull/1843
Feel free to reopen the issue if the problem persists

**Closed by peterychang** 2019-04-12 20:37 UTC
Labels: Build Issue, Distribution Issue, Lang: Python
